In [ ]:
import numpy as np
from copy import deepcopy

In [ ]:
x= np.array([1,2,3,4,5])

In [ ]:
x

array([1, 2, 3, 4, 5])

In [ ]:
def sphere_function(x):
  return sum(x**2)

In [ ]:
sphere_function(x)

55

In [ ]:
class problem:
  def __init__(self):
    self.number_of_genes = 8
    self.min_gene_value = -10
    self.max_gene_value = 10
    self.cost_function = sphere_function

In [ ]:
p = problem()

In [ ]:
x=np.array([-1,3,-5,8,3,9,2,0])

In [ ]:
p.cost_function(x)

193

In [ ]:
sphere_function(x)

193

In [ ]:
class individual:
  chromosone = None
  def __init__(self, prob):
    #Create a random individual.
    self.chromosone = np.random.uniform(prob.min_gene_value,prob.max_gene_value,prob.number_of_genes)
    self.cost = prob.cost_function(self.chromosone)

In [ ]:
np.random.uniform(-10,10,8)

array([ 3.16709301, -7.556601  , -0.21119743,  8.43510073, -1.86027444,
       -7.12369716,  2.93069805, -7.29269814])

In [ ]:
class parameters:
  def __init__(self):
    self.number_in_population = 1000
    self.number_of_generations = 500
    self.child_rate = 0.5

In [ ]:
def run_genetic(prob, params):
  #  read the problem
  cost_function = prob.cost_function

  #   read parameters
  number_in_population = params.number_in_population
  number_of_children = params.child_rate * number_in_population

  #  Initialise the population
  best_solution = individual(prob)
  best_solution.cost = 999999

  population = []
  for i in range(number_in_population):
    new_individual = individual(prob)
    population.append(new_individual)
    if new_individual.cost < best_solution.cost:
      best_solution = deepcopy(new_individual)  # copy new_individual


# loop  

  #generate children
  children = []
  while len(children) < number_of_children:


    # choose parents
    parent1_index, parent2_index = choose_different_indices(len(population))
    parent1 = population[parent1_index]
    parent2 = population[parent2_index]
    



    #  cost the children


  # add children to popuation

  # sort and cull population



  return population, best_solution






In [ ]:
para = parameters()

In [ ]:
para

In [ ]:
pop, best_sol = run_genetic(p,para)

In [ ]:
pop[43]

In [ ]:
pop[43]

In [ ]:
i2.cost

209.68058780983174

In [ ]:
i1.chromosone

array([-0.77621579,  9.77864776,  8.03067203, -8.25421896,  1.64978791,
        4.08964589,  5.92886911,  9.04492036])

In [ ]:
def choose_different_indices(max_value):
  index1 = np.random.randint(0,max_value)
  index2 = np.random.randint(0,max_value)
  if index1 == index2:
    return choose_different_indices(max_value)
  return index1, index2

In [ ]:
pop[1000]

IndexError: ignored

In [ ]:
for i in range(200):
  i1, i2 = choose_different_indices(20)
  print("First" + str(i1) + "Second" + str(i2))
 


First17Second11
First15Second6
First10Second8
First4Second11
First12Second19
First3Second9
First13Second14
First6Second19
First6Second1
First11Second16
First17Second7
First18Second4
First9Second5
First10Second12
First6Second16
First4Second9
First15Second10
First3Second6
First10Second1
First7Second3
First10Second15
First18Second2
First19Second6
First15Second9
First2Second10
First12Second19
First16Second17
First6Second8
First16Second17
First17Second2
First7Second0
First3Second6
First11Second10
First17Second2
First17Second7
First16Second4
First5Second3
First10Second9
First16Second9
First11Second4
First1Second4
First17Second16
First12Second17
First13Second1
First11Second8
First7Second18
First3Second15
First16Second2
First9Second11
First0Second14
First15Second19
First12Second2
First14Second13
First9Second1
First1Second15
First0Second5
First18Second15
First13Second19
First6Second18
First15Second11
First15Second17
First15Second14
First19Second15
First14Second19
First9Second16
First3Second9
Fi